import {
  EuiButton,
  EuiFormRow,
  EuiPopover,
  EuiSpacer,
  EuiCallOut,
  EuiLink,
  EuiSwitch,
  EuiBadge,
  EuiLoadingSpinner,
  EuiAvatar,
  EuiCard,
  EuiIcon,
  EuiFlexGroup,
  EuiFlexItem,
  EuiHealth,
  EuiEmptyPrompt,
  EuiDragDropContext,
  EuiDraggable,
  EuiDroppable,
  EuiDescriptionList,
  EuiDescriptionListTitle,
  EuiDescriptionListDescription,
  EuiCode,
  EuiImage,
  EuiListGroup,
  EuiListGroupItem,
  EuiLoadingKibana,
  EuiLoadingChart,
} from "@elastic/eui";
import CircularProgress from "@material-ui/core/CircularProgress";
import styled from "styled-components";

import { makeStyles } from "@material-ui/core/styles";
const scope = {
  EuiButton,
  styled,
  EuiCallOut,
  EuiLink,
  EuiIcon,
  CircularProgress,
  makeStyles,
  EuiFormRow,
  EuiPopover,
  EuiSpacer,
  EuiCard,
  EuiFlexGroup,
  EuiFlexItem,
  EuiSwitch,
  EuiBadge,
  EuiLoadingSpinner,
  EuiAvatar,
  EuiHealth,
  EuiEmptyPrompt,
  EuiDragDropContext,
  EuiDraggable,
  EuiDroppable,
  EuiDescriptionList,
  EuiDescriptionListTitle,
  EuiDescriptionListDescription,
  EuiCode,
  EuiImage,
  EuiListGroup,
  EuiListGroupItem,
  EuiLoadingKibana,
  EuiLoadingChart,
};

export default scope;
